---
# Aufgaben 
###########
#
### Part 1
# 1. String in langen Textfile suchen
# 2. Parameter für bestimmten Befehl suchen
# 3. Ausgabe mit ls und Redirection erzeugen
# 4. Versteckte Datei finden
# 5. Alias ausführen
# 6. Abschnitt in der Manpage für Admin-Befehle
# 7. Installiere Linux-Distro und Major-Version herausfinden
# 8. Dateien vergleichen (Hardlinks)
# 9. Datei mit merkwürdigen Inhalt ausgeben
#
### Part 2
# 10. Wieviele Mitglieder hat die Gruppe jailed
# 11. Nicht lesbare Datei lesbar machen
# 12. Nicht lesbarer Ordner
# 13. Zählen wie oft ein Wort in einer Datei enthalten ist
# 14. Eine Datei finden die keinem User und keiner Gruppe gehört
# 16. Gegenteiltag (Text rückwärts ausgeben lassen)
# 17. Mit Wildcards arbeiten
# 18. Verwendete Kernel-Version herausfinden
# 19. User-Wechsel und Env-Var
#

- name: Erstelle Schnitzeljagd-Ordner
  ansible.builtin.file: 
    path: "/home/{{ item }}/schnitzeljagd"
    mode: '0750'
    owner: "{{ item }}"
    state: directory
    group: users
  loop: "{{ ssh_jailed_users }}"

- name: Erstelle Readme.md, tipps und solution
  ansible.builtin.copy:
    src: "{{ src_dir }}/{{ item[0] }}"
    owner: "{{ item[1] }}"
    group: users
    dest: "/home/{{ item[1] }}/schnitzeljagd/{{ item[0] }}"
  with_nested:
    - "{{ etc_files }}"
    - "{{ ssh_jailed_users }}"

# Erstelle Tage 1
- name: Erstelle Schnitzeljagd
  tags: ['teil1', 'never']
  ansible.builtin.copy:
    src: "{{ src_dir }}/{{ item[0] }}"
    owner: "{{ item[1] }}"
    group: users
    # defaults to umask
    #mode: '0750'
    dest: "/home/{{ item[1] }}/schnitzeljagd/"
  with_nested: 
  - "{{ teil1 }}"
  - "{{ ssh_jailed_users }}"

# Aufgabe 5; finde und führe Alias aus
- name: Erstelle Alias für Aufgabe 5
  tags: ['teil1', 'never']
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.bashrc"
    create: true
    insertafter: "EOF"
    line: "alias quallenfischersong=/etc/quallenfischersong.sh"
    state: present
    owner: "{{ item }}"
    group: users
    mode: '0644'
  loop: "{{ ssh_jailed_users }}"

- name: Lege das Skript ab für Aufgabe 5
  tags: ['teil1', 'never']
  ansible.builtin.copy:
    src: quallenfischersong.sh
    dest: /etc/quallenfischersong.sh
    owner: root
    group: root
    mode: "0755"

# Aufgabe 8; Dateien vergleichen (Hardlinks)
- name: Erstelle Hardlinks
  tags: ['teil1', 'never']
  ansible.builtin.file:
    src: "/home/{{ item[1] }}/schnitzeljagd/08/unterordner/bestellung_5"
    dest: "/home/{{ item[1] }}/schnitzeljagd/08/unterordner/bestellung_{{ item[0] }}"
    state: hard
    owner: "{{ item[1] }}"
    group: users
  with_nested:
   - "{{ ['1', '2', '3', '6', '7', '8', '9'] }}" # Datei-Namen der Hardlinks
   - "{{ ssh_jailed_users }}"

- name: Erstelle Datei für Lösung für Aufgabe 8
  tags: ['teil1', 'never']
  ansible.builtin.copy:
    src: "{{ src_dir }}/08/unterordner/bestellung_5"
    dest: "/home/{{ item }}/schnitzeljagd/08/unterordner/bestellung_04"
    owner: "{{ item }}"
    group: users
  loop: "{{ ssh_jailed_users }}"

# Erstelle Aufgaben für Tag 2
- name: Erstelle Aufgaben für Tag 2 / Teil 2
  tags: ['teil2', 'never']
  ansible.builtin.copy:
    src: "{{ src_dir }}/{{ item[0] }}"
    owner: "{{ item[1] }}"
    group: users
    dest: "/home/{{ item[1] }}/schnitzeljagd/"
  with_nested: 
  - "{{ teil2 }}"
  - "{{ ssh_jailed_users }}"

# Aufgabe 11; nicht lesbare Datei lesbar machen
- name: Passe Berechtigungen für Aufgabe 11 an
  tags: ['teil2', 'never'] 
  ansible.builtin.file:
    path: "/home/{{ item }}/schnitzeljagd/11/text"
    owner: root
    group: root
    mode: '0700'
  loop: "{{ ssh_jailed_users }}"

# Aufgabe 12; nicht lesbaren Ordner lesbar machen
- name: Passe Berechtigungen für Aufgabe 12 an
  tags: ['teil2', 'never']
  ansible.builtin.file:
    path: "/home/{{ item }}/schnitzeljagd/12/unterordner"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: '0000'
  loop: "{{ ssh_jailed_users }}"

# Aufgabe 14; Datei die keinem User und keiner Gruppe gehört
- name: Passe Datei an für Aufgabe 14
  tags: ['teil2', 'never']
  ansible.builtin.file:
    path: "/home/{{ item }}/schnitzeljagd/14/unterordner/Lorem/4/9/10/sometest"
    owner: 500
    group: 500
  loop: "{{ ssh_jailed_users }}"

# Aufgabe 19; env-Variable für Plankton; Test mit User-Service und linger-User
- name: Erstelle Ordnerstruktur für SystemD-Service
  tags: ['teil2', 'never']
  ansible.builtin.file:
    path: /home/plankton/.config/systemd/user
    state: directory
    owner: plankton
    group: users
    mode: 0755

- name: Erstelle Env-Service für Aufgabe 19
  tags: ['teil2', 'never']
  ansible.builtin.template:
    src: set_env@service
    dest: /home/plankton/.config/systemd/user/set-env.service
    owner: plankton
    group: users
    mode: '0644'

- name: Enable Linger User
  ansible.builtin.command: 
    cmd: "/usr/bin/loginctl enable-linger plankton"