---
- name: Erstelle Schnitzeljagd
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    src_dir: ~/workshop_exercise/schnitzeljagd
    teil1: ['01', '02', '03', '04', '05', '06', '07', '08', ' 09']
    teil2: ['10', '11', '12', '13', '14', '15', '16', '17, '18', '19'] 
    etc_files: ['Readme.md', 'solution', 'tipps']

  vars_files: ~/webtty-playground/vars/jailed.yml

  roles:
    - create-user
    - create-exercises