---
- name: Erstelle Schnitzeljagd
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    src_dir: ~/workshop_exercise/schnitzeljagd

  vars_files: ~/webtty-playground/vars/jailed.yml

  roles:
    - create-user
    - create-exercises