---
- name: Erstelle Schnitzeljagd
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    src_dir: ~/workshop_exercise/schnitzeljagd
    teil1: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11']
    teil2: ['12', '13', '14', '15', '16', '17', '18', '19', '20', '21'] 
    etc_files: ['00_readme.md', '00_solution', '00_tipps']
    sidequests: ['01', '02']

  vars_files: ~/webtty-playground/vars/jailed.yml

  roles:
    - create-user
    - create-exercises

# Aufruf mit Tags; teil1 legt Aufgaben für Tag 1 an, teil2 für Tag 2
#
# ansible-playbook setup-exercises.yaml --tags=teil1

### Lösung der Übungsaufgaben geben von folgenden Ergebnissen aus
#
# Kernel-Major-Version 6
# Debian-Major-Version 12
# 11 Workshop-Teilnehmer